# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Shared test helpers for the cookie-reader test suite."""

from __future__ import annotations

import hashlib

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes


def encrypt_chromium_value(
    value: str, password: str, host_key: str, *, with_host_hash: bool = False
) -> bytes:
    """Produce a macOS-Chromium `v10` encrypted_value blob for `value`.

    Mirrors the decryption algorithm under test: PBKDF2-SHA1 key derivation,
    AES-128-CBC with a 16-space IV, optional 32-byte SHA256(host_key) prefix.
    """
    key = hashlib.pbkdf2_hmac("sha1", password.encode(), b"saltysalt", 1003, 16)
    plain = value.encode("utf-8")
    if with_host_hash:
        plain = hashlib.sha256(host_key.encode("utf-8")).digest() + plain
    pad = 16 - (len(plain) % 16)
    plain += bytes([pad]) * pad
    cipher = Cipher(algorithms.AES(key), modes.CBC(b" " * 16))
    enc = cipher.encryptor()
    return b"v10" + enc.update(plain) + enc.finalize()
