# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

from __future__ import annotations

import sqlite3
from pathlib import Path

from salesforce_mcp_auto_auth_chrome import cookies, firefox
from salesforce_mcp_auto_auth_chrome.browsers import CookieSource


def _src(browser: str, family: str) -> CookieSource:
    return CookieSource(browser, "Default", family, Path("/x"), None, None)


# --- firefox.list_salesforce_sids -------------------------------------------


def test_firefox_lists_only_salesforce_sids(tmp_path):
    db = tmp_path / "cookies.sqlite"
    con = sqlite3.connect(db)
    con.execute("CREATE TABLE moz_cookies (host TEXT, name TEXT, value TEXT)")
    con.executemany(
        "INSERT INTO moz_cookies (host, name, value) VALUES (?, ?, ?)",
        [
            (".cresa.my.salesforce.com", "sid", "MYSID"),
            (".example.com", "sid", "NOPE"),
            (".cresa.my.salesforce.com", "other", "x"),
        ],
    )
    con.commit()
    con.close()

    result = firefox.list_salesforce_sids(
        CookieSource("firefox", "p", "firefox", db, None, None)
    )

    assert result == [(".cresa.my.salesforce.com", "MYSID")]


# --- discover_orgs -----------------------------------------------------------


def test_discover_orgs_maps_lightning_and_ranks_my_domain_first(monkeypatch):
    src = _src("chrome", "chromium")
    monkeypatch.setattr(cookies, "discover_sources", lambda b, p: [src])
    monkeypatch.setattr(
        cookies.chromium,
        "list_salesforce_sids",
        lambda s: [
            (".cresa.lightning.force.com", "LIGHTNING_SID"),
            (".cresa.my.salesforce.com", "MY_SID"),
        ],
    )

    orgs = cookies.discover_orgs()

    pairs = [(o.instance_url, o.sid) for o in orgs]
    assert pairs[0] == ("https://cresa.my.salesforce.com", "MY_SID")  # primary first
    assert ("https://cresa.my.salesforce.com", "LIGHTNING_SID") in pairs


def test_discover_orgs_dedupes(monkeypatch):
    src = _src("chrome", "chromium")
    monkeypatch.setattr(cookies, "discover_sources", lambda b, p: [src])
    monkeypatch.setattr(
        cookies.chromium,
        "list_salesforce_sids",
        lambda s: [(".cresa.my.salesforce.com", "SID")] * 3,
    )

    assert len(cookies.discover_orgs()) == 1


# --- resolve_session ---------------------------------------------------------


def test_resolve_configured_normalizes_and_pins_source(monkeypatch):
    monkeypatch.setattr(
        cookies,
        "read_sid_with_source",
        lambda u, b, p: (
            ("SID", "comet", "Profile 1")
            if u == "https://cresa.my.salesforce.com"
            else None
        ),
    )

    r = cookies.resolve_session("https://cresa.lightning.force.com")

    assert r.instance_url == "https://cresa.my.salesforce.com"
    assert r.sid == "SID"
    assert (r.browser, r.profile) == ("comet", "Profile 1")


def test_resolve_autodiscovers_first_valid_with_source(monkeypatch):
    monkeypatch.setattr(cookies, "read_sid_with_source", lambda u, b, p: None)
    cands = [
        cookies.OrgCandidate(
            "https://cresa.my.salesforce.com", "LIGHTNING", "chrome", "Profile 6"
        ),
        cookies.OrgCandidate(
            "https://cresa.my.salesforce.com", "GOOD", "chrome", "Profile 4"
        ),
    ]
    monkeypatch.setattr(cookies, "discover_orgs", lambda b, p: cands)
    monkeypatch.setattr(cookies, "session_is_valid", lambda u, s: s == "GOOD")

    r = cookies.resolve_session(None)

    assert (r.instance_url, r.sid) == ("https://cresa.my.salesforce.com", "GOOD")
    assert (r.browser, r.profile) == ("chrome", "Profile 4")


def test_resolve_returns_empty_when_nothing_found(monkeypatch):
    monkeypatch.setattr(cookies, "read_sid_with_source", lambda u, b, p: None)
    monkeypatch.setattr(cookies, "discover_orgs", lambda b, p: [])

    r = cookies.resolve_session(None)
    assert (r.instance_url, r.sid) == (None, None)


def test_resolve_defers_error_for_configured_without_session(monkeypatch):
    monkeypatch.setattr(cookies, "read_sid_with_source", lambda u, b, p: None)
    monkeypatch.setattr(cookies, "discover_orgs", lambda b, p: [])

    r = cookies.resolve_session("https://cresa.lightning.force.com")

    assert r.instance_url == "https://cresa.my.salesforce.com"
    assert r.sid is None
