# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

from __future__ import annotations

import simple_salesforce

from salesforce_mcp_auto_auth_chrome import patch


class _FakeSF:
    """Minimal stand-in for simple_salesforce.Salesforce for patch testing."""

    def __init__(self) -> None:
        self.session_id = "OLD"
        self.headers = {"Authorization": "Bearer OLD"}


def _install_capturing(monkeypatch, **kwargs):
    """Install the patch over a no-op original; return the patched method + sink."""
    calls = {}

    def _orig(self, method, url, name="", retries=0, max_retries=3, **kw):
        calls["session_id"] = self.session_id
        calls["auth"] = self.headers["Authorization"]
        return "OK"

    monkeypatch.setattr(
        simple_salesforce.Salesforce, "_call_salesforce", _orig, raising=False
    )
    patch.install("https://cresa.my.salesforce.com", **kwargs)
    return simple_salesforce.Salesforce._call_salesforce, calls


def test_prefers_pinned_profile(monkeypatch):
    seen = []

    def fake_read_sid(url, browsers=None, profiles=None):
        seen.append((browsers, profiles))
        return "PINNED_SID" if browsers == ["chrome"] else "FALLBACK_SID"

    monkeypatch.setattr(patch, "read_sid", fake_read_sid)
    patched, calls = _install_capturing(
        monkeypatch,
        pin_browser="chrome",
        pin_profile="Profile 4",
        browsers=None,
        profiles=None,
    )

    result = patched(_FakeSF(), "GET", "https://x")

    assert result == "OK"
    assert calls["auth"] == "Bearer PINNED_SID"
    assert seen[0] == (["chrome"], ["Profile 4"])  # pinned tried first


def test_falls_back_when_pinned_profile_has_no_sid(monkeypatch):
    def fake_read_sid(url, browsers=None, profiles=None):
        if browsers == ["chrome"]:
            return None  # pinned profile logged out
        return "FALLBACK_SID"

    monkeypatch.setattr(patch, "read_sid", fake_read_sid)
    patched, calls = _install_capturing(
        monkeypatch, pin_browser="chrome", pin_profile="Profile 4"
    )

    patched(_FakeSF(), "GET", "https://x")

    assert calls["auth"] == "Bearer FALLBACK_SID"


def test_raises_when_no_sid_anywhere(monkeypatch):
    import pytest

    monkeypatch.setattr(patch, "read_sid", lambda u, b=None, p=None: None)
    patched, _ = _install_capturing(monkeypatch, pin_browser="chrome")

    with pytest.raises(RuntimeError, match="Not logged into Salesforce"):
        patched(_FakeSF(), "GET", "https://x")
