# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

from __future__ import annotations

from pathlib import Path

from salesforce_mcp_auto_auth_chrome import browsers
from salesforce_mcp_auto_auth_chrome.browsers import BrowserConfig, discover_sources


def _fake_chromium(tmp_path: Path) -> BrowserConfig:
    base = tmp_path / "Chrome"
    for name in ("Default", "Profile 1", "System Profile"):
        (base / name).mkdir(parents=True)
        (base / name / "Cookies").write_bytes(b"")
    return BrowserConfig("chrome", "chromium", base, "Chrome Safe Storage", "Chrome")


def test_discover_enumerates_chromium_profiles_excluding_system(tmp_path, monkeypatch):
    cfg = _fake_chromium(tmp_path)
    monkeypatch.setattr(browsers, "BROWSERS", (cfg,))

    sources = discover_sources()

    names = sorted(s.profile for s in sources)
    assert names == ["Default", "Profile 1"]
    assert all(s.browser == "chrome" and s.family == "chromium" for s in sources)
    assert all(s.path.name == "Cookies" for s in sources)


def test_discover_filters_by_browser_key_and_order(tmp_path, monkeypatch):
    chrome = _fake_chromium(tmp_path)
    comet_base = tmp_path / "Comet"
    (comet_base / "Default").mkdir(parents=True)
    (comet_base / "Default" / "Cookies").write_bytes(b"")
    comet = BrowserConfig(
        "comet", "chromium", comet_base, "Comet Safe Storage", "Comet"
    )
    monkeypatch.setattr(browsers, "BROWSERS", (chrome, comet))

    sources = discover_sources(browsers=["comet", "chrome"])

    assert sources[0].browser == "comet"  # requested order wins
    assert {s.browser for s in sources} == {"comet", "chrome"}


def test_discover_filters_by_profile_name(tmp_path, monkeypatch):
    monkeypatch.setattr(browsers, "BROWSERS", (_fake_chromium(tmp_path),))

    sources = discover_sources(profiles=["default"])  # case-insensitive

    assert [s.profile for s in sources] == ["Default"]


def test_discover_skips_missing_base_dir(tmp_path, monkeypatch):
    cfg = BrowserConfig("chrome", "chromium", tmp_path / "nope", "S", "A")
    monkeypatch.setattr(browsers, "BROWSERS", (cfg,))

    assert discover_sources() == []
