# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

from __future__ import annotations

import pytest

from salesforce_mcp_auto_auth_chrome import auth


def test_read_sid_from_chrome_is_chrome_scoped(monkeypatch):
    captured = {}

    def fake_read_sid(url, browsers=None, profiles=None):
        captured["browsers"] = browsers
        return "SID"

    monkeypatch.setattr(auth, "read_sid", fake_read_sid)

    with pytest.warns(DeprecationWarning):
        result = auth.read_sid_from_chrome("https://acme.my.salesforce.com")

    assert result == "SID"
    assert captured["browsers"] == ["chrome"]
