# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

from __future__ import annotations

import urllib.error

from salesforce_mcp_auto_auth_chrome import validate
from salesforce_mcp_auto_auth_chrome.validate import session_is_valid


class _Resp:
    def __init__(self, status: int) -> None:
        self.status = status

    def __enter__(self):
        return self

    def __exit__(self, *a):
        return False


def test_valid_session_returns_true(monkeypatch):
    captured = {}

    def fake_urlopen(req, timeout=0):
        captured["url"] = req.full_url
        captured["auth"] = req.get_header("Authorization")
        return _Resp(200)

    monkeypatch.setattr(validate, "urlopen", fake_urlopen)

    assert session_is_valid("https://cresa.my.salesforce.com", "THE_SID") is True
    assert captured["url"] == "https://cresa.my.salesforce.com/services/oauth2/userinfo"
    assert captured["auth"] == "Bearer THE_SID"


def test_http_401_returns_false(monkeypatch):
    def fake_urlopen(req, timeout=0):
        raise urllib.error.HTTPError(req.full_url, 401, "Unauthorized", {}, None)

    monkeypatch.setattr(validate, "urlopen", fake_urlopen)

    assert session_is_valid("https://cresa.my.salesforce.com", "BAD_SID") is False


def test_network_error_returns_false(monkeypatch):
    def fake_urlopen(req, timeout=0):
        raise urllib.error.URLError("no route")

    monkeypatch.setattr(validate, "urlopen", fake_urlopen)

    assert session_is_valid("https://cresa.my.salesforce.com", "SID") is False
