# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

from __future__ import annotations

import sqlite3
from pathlib import Path

from salesforce_mcp_auto_auth_chrome import chromium
from salesforce_mcp_auto_auth_chrome.browsers import CookieSource
from tests.conftest import encrypt_chromium_value

_PASSWORD = "test-safe-storage-key"


def _make_db(path: Path, rows: list[tuple[str, str, bytes]]) -> None:
    con = sqlite3.connect(path)
    con.execute(
        "CREATE TABLE cookies (host_key TEXT, name TEXT, value TEXT, "
        "encrypted_value BLOB)"
    )
    con.executemany(
        "INSERT INTO cookies (host_key, name, value, encrypted_value) "
        "VALUES (?, ?, ?, ?)",
        [(h, "sid", v, e) for (h, v, e) in rows],
    )
    con.commit()
    con.close()


def _source(path: Path) -> CookieSource:
    return CookieSource(
        "chrome",
        "Default",
        "chromium",
        path,
        "Chrome Safe Storage",
        "Chrome",
    )


def test_reads_encrypted_sid(tmp_path, monkeypatch):
    host = ".my.salesforce.com"
    enc = encrypt_chromium_value("THE_SID_VALUE", _PASSWORD, host)
    db = tmp_path / "Cookies"
    _make_db(db, [(host, "", enc)])
    monkeypatch.setattr(chromium, "_keychain_password", lambda s, a: _PASSWORD)

    assert (
        chromium.read_chromium_cookie(_source(db), "acme.my.salesforce.com", "sid")
        == "THE_SID_VALUE"
    )


def test_strips_host_hash_prefix(tmp_path, monkeypatch):
    host = "acme.my.salesforce.com"
    enc = encrypt_chromium_value("HASHED_SID", _PASSWORD, host, with_host_hash=True)
    db = tmp_path / "Cookies"
    _make_db(db, [(host, "", enc)])
    monkeypatch.setattr(chromium, "_keychain_password", lambda s, a: _PASSWORD)

    assert chromium.read_chromium_cookie(_source(db), host, "sid") == "HASHED_SID"


def test_prefers_longest_host_suffix_match(tmp_path, monkeypatch):
    db = tmp_path / "Cookies"
    _make_db(
        db,
        [
            (
                ".salesforce.com",
                "",
                encrypt_chromium_value("WRONG", _PASSWORD, ".salesforce.com"),
            ),
            (
                "acme.my.salesforce.com",
                "",
                encrypt_chromium_value("RIGHT", _PASSWORD, "acme.my.salesforce.com"),
            ),
        ],
    )
    monkeypatch.setattr(chromium, "_keychain_password", lambda s, a: _PASSWORD)

    assert (
        chromium.read_chromium_cookie(_source(db), "acme.my.salesforce.com", "sid")
        == "RIGHT"
    )


def test_returns_plaintext_value_when_present(tmp_path, monkeypatch):
    db = tmp_path / "Cookies"
    _make_db(db, [(".my.salesforce.com", "PLAINTEXT_SID", b"")])
    monkeypatch.setattr(chromium, "_keychain_password", lambda s, a: None)

    assert (
        chromium.read_chromium_cookie(_source(db), "acme.my.salesforce.com", "sid")
        == "PLAINTEXT_SID"
    )


def test_returns_none_when_keychain_unavailable(tmp_path, monkeypatch):
    host = ".my.salesforce.com"
    db = tmp_path / "Cookies"
    _make_db(db, [(host, "", encrypt_chromium_value("X", _PASSWORD, host))])
    monkeypatch.setattr(chromium, "_keychain_password", lambda s, a: None)

    assert (
        chromium.read_chromium_cookie(_source(db), "acme.my.salesforce.com", "sid")
        is None
    )


def test_returns_none_when_no_matching_host(tmp_path, monkeypatch):
    db = tmp_path / "Cookies"
    _make_db(
        db,
        [(".example.com", "", encrypt_chromium_value("X", _PASSWORD, ".example.com"))],
    )
    monkeypatch.setattr(chromium, "_keychain_password", lambda s, a: _PASSWORD)

    assert (
        chromium.read_chromium_cookie(_source(db), "acme.my.salesforce.com", "sid")
        is None
    )
