# Generated by OrchestKit Claude Plugin
# Created: 2026-06-29

from __future__ import annotations

import json

from salesforce_mcp_auto_auth_chrome import useragent


def _fake_urlopen(payload):
    """Return a urlopen stand-in yielding `payload` (dict) as a JSON response."""

    class _Resp:
        def __enter__(self):
            return self

        def __exit__(self, *exc):
            return False

        def read(self):
            return json.dumps(payload).encode("utf-8")

    def _open(url, timeout=1.0):
        return _Resp()

    return _open


def test_env_override_wins(monkeypatch):
    # Even with a live browser available, an explicit override takes priority.
    monkeypatch.setattr(useragent, "_ua_from_cdp", lambda port, timeout=1.0: "CDP-UA")
    ua = useragent.resolve_user_agent(env={useragent.ENV_VAR: "  My/UA 1.0  "})
    assert ua == "My/UA 1.0"  # trimmed


def test_blank_env_override_is_ignored(monkeypatch):
    monkeypatch.setattr(useragent, "_ua_from_cdp", lambda port, timeout=1.0: "CDP-UA")
    ua = useragent.resolve_user_agent(env={useragent.ENV_VAR: "   "})
    assert ua == "CDP-UA"


def test_uses_live_cdp_when_no_override(monkeypatch):
    monkeypatch.setattr(
        useragent,
        "urlopen",
        _fake_urlopen({"User-Agent": "Mozilla/5.0 Chrome/149.0.0.0 Safari/537.36"}),
    )
    ua = useragent.resolve_user_agent(env={}, cdp_ports=(9222,))
    assert ua == "Mozilla/5.0 Chrome/149.0.0.0 Safari/537.36"


def test_strips_headless_marker(monkeypatch):
    monkeypatch.setattr(
        useragent,
        "urlopen",
        _fake_urlopen({"User-Agent": "Mozilla/5.0 HeadlessChrome/149.0.0.0 Safari"}),
    )
    ua = useragent.resolve_user_agent(env={}, cdp_ports=(9222,))
    assert "Headless" not in ua
    assert "Chrome/149.0.0.0" in ua


def test_falls_back_when_no_browser(monkeypatch):
    # No override, and the CDP probe fails for every port.
    monkeypatch.setattr(useragent, "_ua_from_cdp", lambda port, timeout=1.0: None)
    ua = useragent.resolve_user_agent(env={}, cdp_ports=(9222, 9333))
    assert ua == useragent.FALLBACK_UA


def test_cdp_probe_swallows_connection_errors(monkeypatch):
    def _boom(url, timeout=1.0):
        raise OSError("connection refused")

    monkeypatch.setattr(useragent, "urlopen", _boom)
    assert useragent._ua_from_cdp(9222) is None


def test_cdp_probe_rejects_non_browser_ua(monkeypatch):
    monkeypatch.setattr(
        useragent, "urlopen", _fake_urlopen({"User-Agent": "python-requests/2.x"})
    )
    # Missing the "Mozilla" marker → treated as not-a-browser, returns None.
    assert useragent._ua_from_cdp(9222) is None
