# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

from __future__ import annotations

from pathlib import Path

from salesforce_mcp_auto_auth_chrome import cookies
from salesforce_mcp_auto_auth_chrome.browsers import CookieSource


def _src(browser: str, family: str) -> CookieSource:
    return CookieSource(browser, "Default", family, Path("/x"), None, None)


def test_returns_first_nonempty_sid_in_priority_order(monkeypatch):
    sources = [_src("chrome", "chromium"), _src("comet", "chromium")]
    monkeypatch.setattr(cookies, "discover_sources", lambda b, p: sources)
    # chrome has no sid, comet does
    monkeypatch.setattr(
        cookies,
        "read_chromium_cookie",
        lambda s, h, n: "COMET_SID" if s.browser == "comet" else None,
    )

    assert cookies.read_sid("https://acme.my.salesforce.com") == "COMET_SID"


def test_dispatches_by_family(monkeypatch):
    monkeypatch.setattr(
        cookies, "discover_sources", lambda b, p: [_src("safari", "safari")]
    )
    monkeypatch.setattr(cookies, "read_safari_cookie", lambda s, h, n: "SAFARI_SID")

    assert cookies.read_sid("https://acme.my.salesforce.com") == "SAFARI_SID"


def test_skips_sources_that_raise(monkeypatch):
    def boom(s, h, n):
        raise RuntimeError("locked")

    sources = [_src("chrome", "chromium"), _src("firefox", "firefox")]
    monkeypatch.setattr(cookies, "discover_sources", lambda b, p: sources)
    monkeypatch.setattr(cookies, "read_chromium_cookie", boom)
    monkeypatch.setattr(cookies, "read_firefox_cookie", lambda s, h, n: "FF_SID")

    assert cookies.read_sid("https://acme.my.salesforce.com") == "FF_SID"


def test_returns_none_for_bad_url(monkeypatch):
    monkeypatch.setattr(cookies, "discover_sources", lambda b, p: [])
    assert cookies.read_sid("not-a-url") is None


def test_parse_env_reads_lists():
    env = {"SALESFORCE_BROWSERS": "comet, chrome", "SALESFORCE_PROFILES": "Default"}
    assert cookies.parse_env(env) == (["comet", "chrome"], ["Default"])


def test_parse_env_empty_returns_none():
    assert cookies.parse_env({}) == (None, None)
