# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

from __future__ import annotations

from salesforce_mcp_auto_auth_chrome.instance import (
    is_salesforce_host,
    normalize_host,
    normalize_instance_url,
)


def test_lightning_maps_to_my_domain():
    assert normalize_host("acme.lightning.force.com") == "acme.my.salesforce.com"


def test_sandbox_lightning_maps_to_my_domain():
    assert (
        normalize_host("acme--uat.sandbox.lightning.force.com")
        == "acme--uat.sandbox.my.salesforce.com"
    )


def test_my_domain_unchanged():
    assert normalize_host("acme.my.salesforce.com") == "acme.my.salesforce.com"


def test_leading_dot_and_case_stripped():
    assert normalize_host(".ACME.Lightning.Force.Com") == "acme.my.salesforce.com"


def test_normalize_instance_url_adds_scheme_and_maps():
    assert (
        normalize_instance_url("acme.lightning.force.com")
        == "https://acme.my.salesforce.com"
    )


def test_normalize_instance_url_preserves_my_domain():
    assert (
        normalize_instance_url("https://acme.my.salesforce.com/lightning/o/Account")
        == "https://acme.my.salesforce.com"
    )


def test_normalize_instance_url_none_for_garbage():
    assert normalize_instance_url("") is None


def test_is_salesforce_host():
    assert is_salesforce_host("acme.my.salesforce.com")
    assert is_salesforce_host(".acme.lightning.force.com")
    assert is_salesforce_host("na139.salesforce.com")
    assert not is_salesforce_host("example.com")
