# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

from __future__ import annotations

import sqlite3
from pathlib import Path

from salesforce_mcp_auto_auth_chrome.browsers import CookieSource
from salesforce_mcp_auto_auth_chrome.firefox import (
    list_salesforce_sids,
    read_firefox_cookie,
)


def _make_db(path: Path, rows: list[tuple[str, str]]) -> None:
    con = sqlite3.connect(path)
    con.execute("CREATE TABLE moz_cookies (host TEXT, name TEXT, value TEXT)")
    con.executemany(
        "INSERT INTO moz_cookies (host, name, value) VALUES (?, 'sid', ?)",
        rows,
    )
    con.commit()
    con.close()


def _source(path: Path) -> CookieSource:
    return CookieSource("firefox", "p.default", "firefox", path, None, None)


def test_reads_plaintext_sid(tmp_path):
    db = tmp_path / "cookies.sqlite"
    _make_db(db, [(".my.salesforce.com", "FF_SID")])

    assert read_firefox_cookie(_source(db), "acme.my.salesforce.com", "sid") == "FF_SID"


def test_prefers_longest_host_suffix_match(tmp_path):
    db = tmp_path / "cookies.sqlite"
    _make_db(db, [(".salesforce.com", "WRONG"), ("acme.my.salesforce.com", "RIGHT")])

    assert read_firefox_cookie(_source(db), "acme.my.salesforce.com", "sid") == "RIGHT"


def test_returns_none_when_no_match(tmp_path):
    db = tmp_path / "cookies.sqlite"
    _make_db(db, [(".example.com", "X")])

    assert read_firefox_cookie(_source(db), "acme.my.salesforce.com", "sid") is None


def test_lists_only_salesforce_sids(tmp_path):
    db = tmp_path / "cookies.sqlite"
    con = sqlite3.connect(db)
    con.execute("CREATE TABLE moz_cookies (host TEXT, name TEXT, value TEXT)")
    con.executemany(
        "INSERT INTO moz_cookies (host, name, value) VALUES (?, ?, ?)",
        [
            (".acme.my.salesforce.com", "sid", "MYSID"),
            (".example.com", "sid", "NOPE"),
            (".acme.my.salesforce.com", "other", "x"),
        ],
    )
    con.commit()
    con.close()

    result = list_salesforce_sids(_source(db))

    assert result == [(".acme.my.salesforce.com", "MYSID")]
