# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

from __future__ import annotations

import struct
from pathlib import Path

from salesforce_mcp_auto_auth_chrome.browsers import CookieSource
from salesforce_mcp_auto_auth_chrome.safari import (
    parse_binarycookies,
    read_safari_cookie,
)


def _build_cookie(host: str, name: str, value: str) -> bytes:
    """Build one binarycookies cookie record (offsets relative to record)."""
    header_len = 56  # 14 little-endian 4-byte fields
    url = host.encode() + b"\x00"
    nm = name.encode() + b"\x00"
    path = b"/\x00"
    val = value.encode() + b"\x00"
    url_off = header_len
    name_off = url_off + len(url)
    path_off = name_off + len(nm)
    value_off = path_off + len(path)
    total = value_off + len(val)
    header = struct.pack(
        "<iiii iiii i i dd",
        total,
        0,
        0,
        0,
        url_off,
        name_off,
        path_off,
        value_off,
        0,
        0,  # 8-byte end-of-header marker (two ints)
        0.0,
        0.0,  # expiry, creation (mac epoch doubles)
    )
    return header + url + nm + path + val


def _build_page(cookies: list[bytes]) -> bytes:
    n = len(cookies)
    header = struct.pack("<i", 0x00000100) + struct.pack("<i", n)
    offsets_table_len = 4 * n + 4  # +4 trailing footer field
    base = len(header) + offsets_table_len
    offsets = b""
    running = base
    for c in cookies:
        offsets += struct.pack("<i", running)
        running += len(c)
    offsets += struct.pack("<i", 0)  # page footer
    return header + offsets + b"".join(cookies)


def _build_file(pages: list[bytes]) -> bytes:
    magic = b"cook"
    count = struct.pack(">i", len(pages))
    sizes = b"".join(struct.pack(">i", len(p)) for p in pages)
    return magic + count + sizes + b"".join(pages)


def _source(path: Path) -> CookieSource:
    return CookieSource("safari", "default", "safari", path, None, None)


def test_parse_roundtrip():
    data = _build_file(
        [
            _build_page(
                [
                    _build_cookie(".my.salesforce.com", "sid", "SAFARI_SID"),
                    _build_cookie(".example.com", "other", "nope"),
                ]
            )
        ]
    )

    parsed = parse_binarycookies(data)

    assert (".my.salesforce.com", "sid", "SAFARI_SID") in parsed


def test_read_safari_cookie_matches_host(tmp_path):
    data = _build_file(
        [
            _build_page(
                [
                    _build_cookie(".my.salesforce.com", "sid", "SAFARI_SID"),
                ]
            )
        ]
    )
    f = tmp_path / "Cookies.binarycookies"
    f.write_bytes(data)

    assert (
        read_safari_cookie(_source(f), "acme.my.salesforce.com", "sid") == "SAFARI_SID"
    )


def test_read_safari_cookie_missing_file(tmp_path):
    assert (
        read_safari_cookie(_source(tmp_path / "nope.binarycookies"), "x.com", "sid")
        is None
    )


def test_parse_rejects_bad_magic():
    import pytest

    with pytest.raises(ValueError):
        parse_binarycookies(b"nope" + b"\x00" * 20)
