# Generated by OrchestKit Claude Plugin
# Created: 2026-06-22

"""Tests for the `__main__` entry-point orchestration.

`main()` wires together org resolution, env seeding, the per-call patch, and the
handoff to mcp-salesforce-connector. We stub the three external touch-points
(resolution, the patch installer, and the connector entry point) so the test
exercises only the orchestration logic — no browsers, no Keychain, no network,
and no real MCP server.
"""

from __future__ import annotations

import os
import sys
import types

import pytest

from salesforce_mcp_auto_auth_chrome import __main__ as entry
from salesforce_mcp_auto_auth_chrome.patch import PENDING_LOGIN_SENTINEL

_URL = "https://example.my.salesforce.com"


class _Resolved:
    """Stand-in for `orgs.ResolvedSession`."""

    def __init__(self, instance_url, sid, browser=None, profile=None):
        self.instance_url = instance_url
        self.sid = sid
        self.browser = browser
        self.profile = profile


@pytest.fixture
def harness(monkeypatch):
    """Stub the patch installer + connector; capture env at connector-run time."""
    state: dict = {"installed": False, "connector_ran": False, "env_at_run": {}}

    def fake_install(instance_url, **kwargs):
        state["installed"] = True
        state["install_args"] = (instance_url, kwargs)

    def connector_main():
        state["connector_ran"] = True
        state["env_at_run"] = {
            "SALESFORCE_INSTANCE_URL": os.environ.get("SALESFORCE_INSTANCE_URL"),
            "SALESFORCE_ACCESS_TOKEN": os.environ.get("SALESFORCE_ACCESS_TOKEN"),
        }
        return 0

    monkeypatch.setattr(entry, "install_patch", fake_install)

    # Inject a fake `src.salesforce` so `from src.salesforce import main` resolves
    # to our recorder instead of starting the real stdio server.
    sales_mod = types.ModuleType("src.salesforce")
    sales_mod.main = connector_main  # type: ignore[attr-defined]
    src_mod = types.ModuleType("src")
    src_mod.salesforce = sales_mod  # type: ignore[attr-defined]
    monkeypatch.setitem(sys.modules, "src", src_mod)
    monkeypatch.setitem(sys.modules, "src.salesforce", sales_mod)

    # Default to a clean macOS env; individual tests override resolution.
    monkeypatch.setattr(sys, "platform", "darwin")
    for var in ("SALESFORCE_INSTANCE_URL", "SALESFORCE_ACCESS_TOKEN"):
        monkeypatch.delenv(var, raising=False)
    return state


def _stub_resolution(monkeypatch, resolved):
    monkeypatch.setattr(entry, "resolve_session", lambda *a, **k: resolved)


def test_happy_path_seeds_env_installs_patch_and_runs(monkeypatch, harness):
    _stub_resolution(monkeypatch, _Resolved(_URL, "SID123", "chrome", "Default"))

    rc = entry.main()

    assert rc == 0
    assert harness["installed"]
    assert harness["connector_ran"]
    assert harness["env_at_run"]["SALESFORCE_INSTANCE_URL"] == _URL
    assert harness["env_at_run"]["SALESFORCE_ACCESS_TOKEN"] == "SID123"
    # The patch is pinned to the resolved source.
    _, kwargs = harness["install_args"]
    assert kwargs["pin_browser"] == "chrome"
    assert kwargs["pin_profile"] == "Default"


def test_missing_instance_url_errors_without_running_connector(monkeypatch, harness):
    _stub_resolution(monkeypatch, _Resolved(None, None))

    rc = entry.main()

    assert rc == 1
    assert not harness["installed"]
    assert not harness["connector_ran"]


def test_sentinel_seeded_when_no_initial_sid(monkeypatch, harness):
    _stub_resolution(monkeypatch, _Resolved(_URL, None, "chrome", "Default"))

    rc = entry.main()

    assert rc == 0
    assert harness["env_at_run"]["SALESFORCE_ACCESS_TOKEN"] == PENDING_LOGIN_SENTINEL


def test_oauth_env_vars_are_cleared(monkeypatch, harness):
    for var in entry._OAUTH_ENV_VARS:
        monkeypatch.setenv(var, "stale-value")
    _stub_resolution(monkeypatch, _Resolved(_URL, "SID", "chrome", "Default"))

    rc = entry.main()

    assert rc == 0
    for var in entry._OAUTH_ENV_VARS:
        assert var not in os.environ


def test_non_darwin_platform_exits_before_resolution(monkeypatch, harness):
    monkeypatch.setattr(sys, "platform", "linux")

    def _boom(*a, **k):
        raise AssertionError("resolve_session must not run on a non-macOS platform")

    monkeypatch.setattr(entry, "resolve_session", _boom)

    rc = entry.main()

    assert rc == 1
    assert not harness["connector_ran"]


def test_parse_env_reads_lists():
    env = {"SALESFORCE_BROWSERS": "comet, chrome", "SALESFORCE_PROFILES": "Default"}
    assert entry.parse_env(env) == (["comet", "chrome"], ["Default"])


def test_parse_env_empty_returns_none():
    assert entry.parse_env({}) == (None, None)


def test_parse_env_skip_excludes_from_full_registry():
    # No allowlist + skip firefox -> every registered browser except firefox.
    browsers, _ = entry.parse_env({"SALESFORCE_SKIP_BROWSERS": "firefox"})
    assert browsers is not None
    assert "firefox" not in browsers
    assert "chrome" in browsers and "safari" in browsers


def test_parse_env_skip_is_case_insensitive():
    browsers, _ = entry.parse_env({"SALESFORCE_SKIP_BROWSERS": "FireFox"})
    assert browsers is not None
    assert "firefox" not in browsers


def test_parse_env_skip_applies_after_allowlist():
    env = {"SALESFORCE_BROWSERS": "comet, firefox, chrome",
           "SALESFORCE_SKIP_BROWSERS": "firefox"}
    browsers, _ = entry.parse_env(env)
    assert browsers == ["comet", "chrome"]  # order preserved, firefox removed


def test_parse_env_skip_all_scans_nothing():
    # Excluding every browser yields an explicit empty list, not None (= all).
    from salesforce_mcp_auto_auth_chrome.browsers import BROWSERS

    all_keys = ",".join(cfg.key for cfg in BROWSERS)
    browsers, _ = entry.parse_env({"SALESFORCE_SKIP_BROWSERS": all_keys})
    assert browsers == []


def test_parse_env_skip_base_excludes_opt_in_firefox():
    # Applying a denylist expands the default scan set, which omits Firefox.
    browsers, _ = entry.parse_env({"SALESFORCE_SKIP_BROWSERS": "safari"})
    assert browsers is not None
    assert "firefox" not in browsers
    assert "safari" not in browsers
    assert "chrome" in browsers


def test_parse_env_firefox_opt_in_via_allowlist():
    # Naming Firefox explicitly is the opt-in; parse_env passes it through.
    browsers, _ = entry.parse_env({"SALESFORCE_BROWSERS": "firefox, chrome"})
    assert browsers == ["firefox", "chrome"]
