# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Browser registry and profile discovery for cookie reading (macOS).

Each supported browser is described by a `BrowserConfig`. Discovery walks each
browser's on-disk data directory and yields one `CookieSource` per profile that
actually contains a cookie store. The registry order is the search priority.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger(__name__)

_HOME = Path.home()
_APP_SUPPORT = _HOME / "Library" / "Application Support"


@dataclass(frozen=True)
class BrowserConfig:
    """Static description of a browser's cookie storage on macOS.

    Args:
        key: Lowercase identifier, e.g. ``"chrome"``.
        family: One of ``"chromium"``, ``"firefox"``, ``"safari"`` — selects
            the reader used for this browser's cookie store.
        base_dir: The browser's data directory (profiles live under it for
            chromium/firefox; for safari this is the Cookies directory).
        keychain_service: macOS Keychain service holding the Safe Storage key
            (chromium only; ``None`` for firefox/safari).
        keychain_account: macOS Keychain account for the Safe Storage key.
    """

    key: str
    family: str
    base_dir: Path
    keychain_service: str | None = None
    keychain_account: str | None = None


@dataclass(frozen=True)
class CookieSource:
    """A single resolved cookie store (one browser profile)."""

    browser: str
    profile: str
    family: str
    path: Path
    keychain_service: str | None
    keychain_account: str | None


# Priority order: first match wins in the orchestrator.
BROWSERS: tuple[BrowserConfig, ...] = (
    BrowserConfig(
        "chrome", "chromium", _APP_SUPPORT / "Google" / "Chrome",
        "Chrome Safe Storage", "Chrome",
    ),
    BrowserConfig(
        "comet", "chromium", _APP_SUPPORT / "Comet",
        "Comet Safe Storage", "Comet",
    ),
    BrowserConfig(
        "arc", "chromium", _APP_SUPPORT / "Arc" / "User Data",
        "Arc Safe Storage", "Arc",
    ),
    BrowserConfig(
        "edge", "chromium", _APP_SUPPORT / "Microsoft Edge",
        "Microsoft Edge Safe Storage", "Microsoft Edge",
    ),
    BrowserConfig(
        "brave", "chromium",
        _APP_SUPPORT / "BraveSoftware" / "Brave-Browser",
        "Brave Safe Storage", "Brave",
    ),
    BrowserConfig(
        "firefox", "firefox", _APP_SUPPORT / "Firefox" / "Profiles",
    ),
    BrowserConfig(
        "safari", "safari",
        _HOME / "Library" / "Containers" / "com.apple.Safari" / "Data"
        / "Library" / "Cookies",
    ),
)

_CHROMIUM_SKIP = {"System Profile", "Guest Profile"}


def _chromium_sources(cfg: BrowserConfig) -> list[CookieSource]:
    out: list[CookieSource] = []
    if not cfg.base_dir.is_dir():
        return out
    for child in sorted(cfg.base_dir.iterdir()):
        if not child.is_dir() or child.name in _CHROMIUM_SKIP:
            continue
        if child.name != "Default" and not child.name.startswith("Profile "):
            continue
        # Newer Chromium uses <profile>/Network/Cookies; macOS today uses
        # <profile>/Cookies. Prefer Network/ when present.
        cookies = child / "Network" / "Cookies"
        if not cookies.is_file():
            cookies = child / "Cookies"
        if cookies.is_file():
            out.append(CookieSource(
                cfg.key, child.name, cfg.family, cookies,
                cfg.keychain_service, cfg.keychain_account,
            ))
    return out


def _firefox_sources(cfg: BrowserConfig) -> list[CookieSource]:
    out: list[CookieSource] = []
    if not cfg.base_dir.is_dir():
        return out
    for child in sorted(cfg.base_dir.iterdir()):
        cookies = child / "cookies.sqlite"
        if child.is_dir() and cookies.is_file():
            out.append(CookieSource(
                cfg.key, child.name, cfg.family, cookies, None, None,
            ))
    return out


def _safari_sources(cfg: BrowserConfig) -> list[CookieSource]:
    cookies = cfg.base_dir / "Cookies.binarycookies"
    if cookies.is_file():
        return [CookieSource(cfg.key, "default", cfg.family, cookies, None, None)]
    return []


def discover_sources(
    browsers: list[str] | None = None,
    profiles: list[str] | None = None,
) -> list[CookieSource]:
    """Enumerate cookie stores across browsers and profiles.

    Args:
        browsers: Optional lowercase browser keys to restrict to, in priority
            order. ``None`` means all registered browsers in registry order.
        profiles: Optional profile names to restrict to (case-insensitive).
            ``None`` means all discovered profiles.

    Returns:
        Resolved `CookieSource` records, in search priority order.
    """
    if browsers is not None:
        wanted = [b.lower() for b in browsers]
        by_key = {cfg.key: cfg for cfg in BROWSERS}
        configs = [by_key[k] for k in wanted if k in by_key]
    else:
        configs = list(BROWSERS)

    profile_filter = {p.lower() for p in profiles} if profiles else None

    sources: list[CookieSource] = []
    for cfg in configs:
        if cfg.family == "chromium":
            found = _chromium_sources(cfg)
        elif cfg.family == "firefox":
            found = _firefox_sources(cfg)
        elif cfg.family == "safari":
            found = _safari_sources(cfg)
        else:  # pragma: no cover — registry is closed
            found = []
        if profile_filter is not None:
            found = [s for s in found if s.profile.lower() in profile_filter]
        sources.extend(found)
    return sources
