# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Browser registry and profile discovery for cookie reading (macOS).

Each supported browser is described by a `BrowserConfig`. Every browser family
has one `CookieReader` adapter (`chromium`/`firefox`/`safari`) registered in
`READERS`; discovery and reading both dispatch through that single registry
rather than switching on `CookieSource.family`. The registry order in `BROWSERS`
is the search priority.
"""

from __future__ import annotations

import logging
from pathlib import Path

from . import chromium, firefox, safari
from .models import BrowserConfig, CookieReader, CookieSource

log = logging.getLogger(__name__)

__all__ = [
    "BrowserConfig",
    "CookieReader",
    "CookieSource",
    "READERS",
    "reader_for",
    "discover_sources",
]

_HOME = Path.home()
_APP_SUPPORT = _HOME / "Library" / "Application Support"


# Priority order: first match wins in the orchestrator.
BROWSERS: tuple[BrowserConfig, ...] = (
    BrowserConfig(
        "chrome",
        "chromium",
        _APP_SUPPORT / "Google" / "Chrome",
        "Chrome Safe Storage",
        "Chrome",
    ),
    BrowserConfig(
        "comet",
        "chromium",
        _APP_SUPPORT / "Comet",
        "Comet Safe Storage",
        "Comet",
    ),
    BrowserConfig(
        "arc",
        "chromium",
        _APP_SUPPORT / "Arc" / "User Data",
        "Arc Safe Storage",
        "Arc",
    ),
    BrowserConfig(
        "edge",
        "chromium",
        _APP_SUPPORT / "Microsoft Edge",
        "Microsoft Edge Safe Storage",
        "Microsoft Edge",
    ),
    BrowserConfig(
        "brave",
        "chromium",
        _APP_SUPPORT / "BraveSoftware" / "Brave-Browser",
        "Brave Safe Storage",
        "Brave",
    ),
    BrowserConfig(
        "firefox",
        "firefox",
        _APP_SUPPORT / "Firefox" / "Profiles",
    ),
    BrowserConfig(
        "safari",
        "safari",
        _HOME
        / "Library"
        / "Containers"
        / "com.apple.Safari"
        / "Data"
        / "Library"
        / "Cookies",
    ),
)

# The single dispatch table: family -> its cookie reader. Every browser family
# in BROWSERS must have an entry here.
READERS: dict[str, CookieReader] = {
    "chromium": chromium.READER,
    "firefox": firefox.READER,
    "safari": safari.READER,
}


def reader_for(family: str) -> CookieReader:
    """Return the `CookieReader` for a browser family (see `READERS`)."""
    return READERS[family]


def discover_sources(
    browsers: list[str] | None = None,
    profiles: list[str] | None = None,
) -> list[CookieSource]:
    """Enumerate cookie stores across browsers and profiles.

    Args:
        browsers: Optional lowercase browser keys to restrict to, in priority
            order. ``None`` means all registered browsers in registry order.
        profiles: Optional profile names to restrict to (case-insensitive).
            ``None`` means all discovered profiles.

    Returns:
        Resolved `CookieSource` records, in search priority order.
    """
    if browsers is not None:
        wanted = [b.lower() for b in browsers]
        by_key = {cfg.key: cfg for cfg in BROWSERS}
        configs = [by_key[k] for k in wanted if k in by_key]
    else:
        configs = list(BROWSERS)

    profile_filter = {p.lower() for p in profiles} if profiles else None

    sources: list[CookieSource] = []
    for cfg in configs:
        found = reader_for(cfg.family).discover(cfg)
        if profile_filter is not None:
            found = [s for s in found if s.profile.lower() in profile_filter]
        sources.extend(found)
    return sources
