# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Read and decrypt Chromium-family cookies on macOS.

Chromium browsers (Chrome, Comet, Arc, Edge, Brave) store cookies in a SQLite
DB. Values are encrypted with a key derived from a per-browser password held in
the macOS Keychain ("<Browser> Safe Storage"). The algorithm: strip the ``v10``
prefix, derive an AES-128 key via PBKDF2-HMAC-SHA1 (salt ``saltysalt``, 1003
iterations), decrypt AES-128-CBC with a 16-space IV, drop PKCS7 padding, and —
for newer Chromium — strip a leading 32-byte ``SHA256(host_key)`` prefix.
"""

from __future__ import annotations

import hashlib
import logging
import shutil
import sqlite3
import subprocess
import tempfile
from pathlib import Path

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

from .browsers import CookieSource

log = logging.getLogger(__name__)

_SALT = b"saltysalt"
_IV = b" " * 16
_ITERATIONS = 1003
_KEY_LEN = 16


def read_chromium_cookie(source: CookieSource, host: str, name: str) -> str | None:
    """Return cookie `name` for `host` from a Chromium cookie store, or None."""
    rows = _query_cookies(source.path, name)
    if rows is None:
        return None
    match = _best_host_match(rows, host)
    if match is None:
        return None
    host_key, value, encrypted = match
    if value:
        return value
    if not encrypted:
        return None
    password = _keychain_password(source.keychain_service, source.keychain_account)
    if not password:
        log.warning(
            "no Keychain password for %s (%s); cannot decrypt cookie",
            source.browser,
            source.keychain_service,
        )
        return None
    try:
        return _decrypt(bytes(encrypted), _derive_key(password), host_key) or None
    except Exception as e:  # noqa: BLE001 — decryption failures must not raise
        log.warning(
            "decrypt failed for %s/%s: %s: %s",
            source.browser,
            source.profile,
            type(e).__name__,
            e,
        )
        return None


def _query_cookies(db_path: Path, name: str) -> list[tuple[str, str, bytes]] | None:
    """Copy the (possibly locked) DB to a temp file and read matching rows."""
    try:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_db = Path(tmp) / "Cookies"
            shutil.copy2(db_path, tmp_db)
            con = sqlite3.connect(f"file:{tmp_db}?mode=ro", uri=True)
            try:
                cur = con.execute(
                    "SELECT host_key, value, encrypted_value FROM cookies "
                    "WHERE name = ?",
                    (name,),
                )
                return [(h, v or "", e or b"") for (h, v, e) in cur.fetchall()]
            finally:
                con.close()
    except Exception as e:  # noqa: BLE001
        log.warning(
            "cookie DB read failed for %s: %s: %s", db_path, type(e).__name__, e
        )
        return None


def _best_host_match(
    rows: list[tuple[str, str, bytes]], host: str
) -> tuple[str, str, bytes] | None:
    """Pick the row whose host_key is the longest suffix-match of `host`."""
    target = host.lower()
    best: tuple[str, str, bytes] | None = None
    best_len = -1
    for host_key, value, encrypted in rows:
        bare = host_key.lstrip(".").lower()
        if target == bare or target.endswith("." + bare):
            if len(bare) > best_len:
                best = (host_key, value, encrypted)
                best_len = len(bare)
    return best


def _derive_key(password: str) -> bytes:
    return hashlib.pbkdf2_hmac(
        "sha1", password.encode("utf-8"), _SALT, _ITERATIONS, _KEY_LEN
    )


def _pkcs7_unpad(data: bytes) -> bytes:
    if not data:
        return data
    pad = data[-1]
    if 1 <= pad <= 16:
        return data[:-pad]
    return data


def _decrypt(encrypted: bytes, key: bytes, host_key: str) -> str | None:
    if encrypted[:3] != b"v10":
        return None
    ciphertext = encrypted[3:]
    cipher = Cipher(algorithms.AES(key), modes.CBC(_IV))
    decryptor = cipher.decryptor()
    plain = decryptor.update(ciphertext) + decryptor.finalize()
    plain = _pkcs7_unpad(plain)
    domain_hash = hashlib.sha256(host_key.encode("utf-8")).digest()
    if plain[:32] == domain_hash:
        plain = plain[32:]
    return plain.decode("utf-8", errors="replace")


def _keychain_password(service: str | None, account: str | None) -> str | None:
    """Fetch the Safe Storage key from the macOS Keychain via `security`."""
    if not service or not account:
        return None
    try:
        result = subprocess.run(
            ["security", "find-generic-password", "-w", "-s", service, "-a", account],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except Exception as e:  # noqa: BLE001
        log.warning("Keychain lookup failed for %s: %s", service, e)
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None
