# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Find a valid Salesforce ``sid`` across all browsers and profiles.

Iterates discovered cookie sources in priority order and returns the first
non-empty ``sid`` cookie matching the instance host. Reading never raises:
any per-source failure is logged and skipped.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping
from urllib.parse import urlparse

from .browsers import CookieSource, discover_sources
from .chromium import read_chromium_cookie
from .firefox import read_firefox_cookie
from .safari import read_safari_cookie

log = logging.getLogger(__name__)


def read_sid(
    instance_url: str,
    browsers: list[str] | None = None,
    profiles: list[str] | None = None,
) -> str | None:
    """Return the first valid Salesforce ``sid`` for `instance_url`, or None.

    Args:
        instance_url: My Domain URL, e.g. ``https://acme.my.salesforce.com``.
        browsers: Optional lowercase browser keys to restrict/order the search.
        profiles: Optional profile names to restrict the search (case-insensitive).

    Returns:
        The ``sid`` string from the highest-priority browser/profile that has a
        live session, or ``None`` if none do.
    """
    host = urlparse(instance_url).hostname
    if not host:
        log.warning("could not parse host from instance_url=%r", instance_url)
        return None

    for source in discover_sources(browsers, profiles):
        try:
            sid = _read_from_source(source, host)
        except Exception as e:  # noqa: BLE001 — never let one source break the loop
            log.warning(
                "source %s/%s failed: %s: %s",
                source.browser,
                source.profile,
                type(e).__name__,
                e,
            )
            continue
        if sid:
            log.info("found sid in %s/%s for %s", source.browser, source.profile, host)
            return sid
    log.info("no sid found in any browser/profile for %s", host)
    return None


def _read_from_source(source: CookieSource, host: str) -> str | None:
    if source.family == "chromium":
        return read_chromium_cookie(source, host, "sid")
    if source.family == "firefox":
        return read_firefox_cookie(source, host, "sid")
    if source.family == "safari":
        return read_safari_cookie(source, host, "sid")
    return None


def parse_env(
    environ: Mapping[str, str],
) -> tuple[list[str] | None, list[str] | None]:
    """Parse ``SALESFORCE_BROWSERS`` / ``SALESFORCE_PROFILES`` env vars.

    Each is a comma-separated list. Returns ``(browsers, profiles)`` where each
    element is a list (order preserved) or ``None`` when unset/empty.
    """
    return _split(environ.get("SALESFORCE_BROWSERS")), _split(
        environ.get("SALESFORCE_PROFILES")
    )


def _split(value: str | None) -> list[str] | None:
    if not value:
        return None
    items = [part.strip() for part in value.split(",") if part.strip()]
    return items or None
