# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Find a valid Salesforce ``sid`` across all browsers and profiles.

Iterates discovered cookie sources in priority order and returns the first
non-empty ``sid`` cookie matching the instance host. Reading never raises:
any per-source failure is logged and skipped.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping
from dataclasses import dataclass
from urllib.parse import urlparse

from . import chromium, firefox, safari
from .browsers import CookieSource, discover_sources
from .chromium import read_chromium_cookie
from .firefox import read_firefox_cookie
from .instance import normalize_instance_url
from .safari import read_safari_cookie
from .validate import session_is_valid

log = logging.getLogger(__name__)

__all__ = [
    "OrgCandidate",
    "ResolvedSession",
    "read_sid",
    "read_sid_with_source",
    "discover_orgs",
    "resolve_session",
    "parse_env",
]


@dataclass(frozen=True)
class OrgCandidate:
    """A discovered Salesforce session: a My Domain REST URL + its sid."""

    instance_url: str
    sid: str
    browser: str
    profile: str


@dataclass(frozen=True)
class ResolvedSession:
    """The org bound at startup, plus the source to pin per-call refresh to.

    ``browser``/``profile`` identify the exact cookie store the initial sid came
    from, so the per-call refresh can keep reading from the *same* profile
    instead of drifting to another profile that happens to hold a stale sid for
    the same host.
    """

    instance_url: str | None
    sid: str | None
    browser: str | None = None
    profile: str | None = None


def read_sid(
    instance_url: str,
    browsers: list[str] | None = None,
    profiles: list[str] | None = None,
) -> str | None:
    """Return the first valid Salesforce ``sid`` for `instance_url`, or None.

    Args:
        instance_url: My Domain URL, e.g. ``https://acme.my.salesforce.com``.
        browsers: Optional lowercase browser keys to restrict/order the search.
        profiles: Optional profile names to restrict the search (case-insensitive).

    Returns:
        The ``sid`` string from the highest-priority browser/profile that has a
        live session, or ``None`` if none do.
    """
    found = read_sid_with_source(instance_url, browsers, profiles)
    return found[0] if found else None


def read_sid_with_source(
    instance_url: str,
    browsers: list[str] | None = None,
    profiles: list[str] | None = None,
) -> tuple[str, str, str] | None:
    """Like `read_sid` but also report where the sid came from.

    Returns ``(sid, browser, profile)`` for the highest-priority source with a
    matching session, or ``None``.
    """
    host = urlparse(instance_url).hostname
    if not host:
        log.warning("could not parse host from instance_url=%r", instance_url)
        return None

    for source in discover_sources(browsers, profiles):
        try:
            sid = _read_from_source(source, host)
        except Exception as e:  # noqa: BLE001 — never let one source break the loop
            log.warning(
                "source %s/%s failed: %s: %s",
                source.browser,
                source.profile,
                type(e).__name__,
                e,
            )
            continue
        if sid:
            log.info("found sid in %s/%s for %s", source.browser, source.profile, host)
            return sid, source.browser, source.profile
    log.info("no sid found in any browser/profile for %s", host)
    return None


def _read_from_source(source: CookieSource, host: str) -> str | None:
    if source.family == "chromium":
        return read_chromium_cookie(source, host, "sid")
    if source.family == "firefox":
        return read_firefox_cookie(source, host, "sid")
    if source.family == "safari":
        return read_safari_cookie(source, host, "sid")
    return None


def _list_sids_from_source(source: CookieSource) -> list[tuple[str, str]]:
    if source.family == "chromium":
        return chromium.list_salesforce_sids(source)
    if source.family == "firefox":
        return firefox.list_salesforce_sids(source)
    if source.family == "safari":
        return safari.list_salesforce_sids(source)
    return []


def discover_orgs(
    browsers: list[str] | None = None,
    profiles: list[str] | None = None,
) -> list[OrgCandidate]:
    """Scan all cookie sources for logged-in Salesforce orgs.

    Each Salesforce ``sid`` cookie is mapped to its My Domain REST URL. Returns
    deduped candidates in priority order, with sids whose cookie was already set
    on a ``my.salesforce.com`` host ranked ahead of Lightning-derived ones (the
    latter carry a different sid that the REST API rejects).
    """
    primary: list[OrgCandidate] = []
    derived: list[OrgCandidate] = []
    seen: set[tuple[str, str]] = set()
    for source in discover_sources(browsers, profiles):
        try:
            pairs = _list_sids_from_source(source)
        except Exception as e:  # noqa: BLE001
            log.warning(
                "listing sids failed for %s/%s: %s: %s",
                source.browser,
                source.profile,
                type(e).__name__,
                e,
            )
            continue
        for host_key, sid in pairs:
            instance_url = normalize_instance_url(host_key)
            if not instance_url:
                continue
            host = instance_url[len("https://") :]
            if not host.endswith("salesforce.com"):
                continue  # Lightning/VF hosts that didn't map to a My Domain
            key = (instance_url, sid)
            if key in seen:
                continue
            seen.add(key)
            candidate = OrgCandidate(instance_url, sid, source.browser, source.profile)
            bare = host_key.lstrip(".").lower()
            (primary if bare.endswith("salesforce.com") else derived).append(candidate)
    return primary + derived


def resolve_session(
    configured_url: str | None,
    browsers: list[str] | None = None,
    profiles: list[str] | None = None,
) -> ResolvedSession:
    """Resolve the org to bind to, an initial ``sid``, and the source to pin.

    Strategy:

    1. If ``configured_url`` is set, normalize it to My Domain and try to read a
       ``sid`` for it directly (trusted — no network probe), recording which
       browser/profile it came from.
    2. Otherwise (or if step 1 found no sid), auto-discover orgs from cookies and
       return the first whose sid validates against the REST API.
    3. If nothing validates, return the normalized configured URL (if any) with
       a ``None`` sid so the error surfaces at tool-call time.
    """
    normalized = normalize_instance_url(configured_url) if configured_url else None
    if normalized:
        found = read_sid_with_source(normalized, browsers, profiles)
        if found:
            sid, browser, profile = found
            return ResolvedSession(normalized, sid, browser, profile)

    for candidate in discover_orgs(browsers, profiles):
        if session_is_valid(candidate.instance_url, candidate.sid):
            log.info(
                "auto-discovered org %s via %s/%s",
                candidate.instance_url,
                candidate.browser,
                candidate.profile,
            )
            return ResolvedSession(
                candidate.instance_url,
                candidate.sid,
                candidate.browser,
                candidate.profile,
            )

    return ResolvedSession(normalized, None, None, None)


def parse_env(
    environ: Mapping[str, str],
) -> tuple[list[str] | None, list[str] | None]:
    """Parse ``SALESFORCE_BROWSERS`` / ``SALESFORCE_PROFILES`` env vars.

    Each is a comma-separated list. Returns ``(browsers, profiles)`` where each
    element is a list (order preserved) or ``None`` when unset/empty.
    """
    return _split(environ.get("SALESFORCE_BROWSERS")), _split(
        environ.get("SALESFORCE_PROFILES")
    )


def _split(value: str | None) -> list[str] | None:
    if not value:
        return None
    items = [part.strip() for part in value.split(",") if part.strip()]
    return items or None
