# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Find a valid Salesforce ``sid`` across all browsers and profiles.

Iterates discovered cookie sources in priority order and returns the first
non-empty ``sid`` cookie matching the instance host. Reading never raises:
any per-source failure is logged and skipped. Choosing *which* org to bind and
validating a session live in ``orgs.py``, which builds on this module.
"""

from __future__ import annotations

import logging
from urllib.parse import urlparse

from .browsers import CookieSource, discover_sources, reader_for

log = logging.getLogger(__name__)

__all__ = ["read_sid", "read_sid_with_source"]


def read_sid(
    instance_url: str,
    browsers: list[str] | None = None,
    profiles: list[str] | None = None,
) -> str | None:
    """Return the first valid Salesforce ``sid`` for `instance_url`, or None.

    Args:
        instance_url: My Domain URL, e.g. ``https://acme.my.salesforce.com``.
        browsers: Optional lowercase browser keys to restrict/order the search.
        profiles: Optional profile names to restrict the search (case-insensitive).

    Returns:
        The ``sid`` string from the highest-priority browser/profile that has a
        live session, or ``None`` if none do.
    """
    found = read_sid_with_source(instance_url, browsers, profiles)
    return found[0] if found else None


def read_sid_with_source(
    instance_url: str,
    browsers: list[str] | None = None,
    profiles: list[str] | None = None,
) -> tuple[str, str, str] | None:
    """Like `read_sid` but also report where the sid came from.

    Returns ``(sid, browser, profile)`` for the highest-priority source with a
    matching session, or ``None``.
    """
    host = urlparse(instance_url).hostname
    if not host:
        log.warning("could not parse host from instance_url=%r", instance_url)
        return None

    for source in discover_sources(browsers, profiles):
        try:
            sid = _read_from_source(source, host)
        except Exception as e:  # noqa: BLE001 — never let one source break the loop
            log.warning(
                "source %s/%s failed: %s: %s",
                source.browser,
                source.profile,
                type(e).__name__,
                e,
            )
            continue
        if sid:
            log.info("found sid in %s/%s for %s", source.browser, source.profile, host)
            return sid, source.browser, source.profile
    log.info("no sid found in any browser/profile for %s", host)
    return None


def _read_from_source(source: CookieSource, host: str) -> str | None:
    return reader_for(source.family).read(source, host, "sid")
