# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Read Firefox cookies on macOS.

Firefox stores cookies unencrypted in ``cookies.sqlite`` (table ``moz_cookies``,
columns ``host``, ``name``, ``value``), so no Keychain/decryption is needed.
"""

from __future__ import annotations

import logging
from pathlib import Path

from .browsers import CookieSource
from .instance import is_salesforce_host
from .utils import best_host_match, query_sqlite_cookies

log = logging.getLogger(__name__)

__all__ = ["list_salesforce_sids", "read_firefox_cookie"]


def list_salesforce_sids(source: CookieSource) -> list[tuple[str, str]]:
    """Return all ``(host, sid)`` Salesforce session cookies in this store."""
    rows = _query_cookies(source.path, "sid")
    if not rows:
        return []
    return [(h, v) for (h, v) in rows if v and is_salesforce_host(h)]


def read_firefox_cookie(source: CookieSource, host: str, name: str) -> str | None:
    """Return cookie `name` for `host` from a Firefox cookie store, or None."""
    rows = _query_cookies(source.path, name)
    if rows is None:
        return None
    # Require a non-empty plaintext value — Firefox cookies are never encrypted.
    match = best_host_match(
        rows, host, host_of=lambda r: r[0], eligible=lambda r: bool(r[1])
    )
    return match[1] if match else None


def _query_cookies(db_path: Path, name: str) -> list[tuple[str, str]] | None:
    """Read ``(host, value)`` rows for cookie ``name`` from ``moz_cookies``."""
    rows = query_sqlite_cookies(
        db_path, "SELECT host, value FROM moz_cookies WHERE name = ?", (name,)
    )
    if rows is None:
        return None
    return [(h, v or "") for (h, v) in rows]
