# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Normalize Salesforce instance URLs to their My Domain REST host.

Salesforce serves the Lightning UI from ``<org>.lightning.force.com`` but the
REST API (and the session cookie that authorizes it) lives on the My Domain
host ``<org>.my.salesforce.com``. The ``sid`` cookie set on the lightning host
is a DIFFERENT value that is rejected by the REST API (INVALID_SESSION_ID). So
before reading cookies or talking to the API we always normalize to My Domain.
"""

from __future__ import annotations

from urllib.parse import urlparse

__all__ = ["normalize_host", "normalize_instance_url", "is_salesforce_host"]

_LIGHTNING_SUFFIX = ".lightning.force.com"
_MY_DOMAIN_SUFFIX = ".my.salesforce.com"


def normalize_host(host: str) -> str:
    """Map a Salesforce UI host to its My Domain REST host.

    ``*.lightning.force.com`` (including sandbox forms) becomes
    ``*.my.salesforce.com``. Any other host is returned lowercased with a
    leading dot stripped.
    """
    h = host.lstrip(".").lower()
    if h.endswith(_LIGHTNING_SUFFIX):
        return h[: -len(_LIGHTNING_SUFFIX)] + _MY_DOMAIN_SUFFIX
    return h


def normalize_instance_url(url: str) -> str | None:
    """Return ``https://<my-domain-host>`` for a Salesforce URL, or None.

    Accepts bare hosts (no scheme), full URLs, and Lightning/My Domain forms.
    """
    if not url:
        return None
    if "://" not in url:
        url = "https://" + url
    host = urlparse(url).hostname
    if not host:
        return None
    return "https://" + normalize_host(host)


def is_salesforce_host(host: str) -> bool:
    """True if `host` is a Salesforce-served host.

    Matches the bare apex (``salesforce.com``/``force.com``) or any subdomain of
    it — the leading label separator is required, so a look-alike registered
    domain such as ``attacker-salesforce.com`` is rejected. Without the dot, a
    ``sid`` cookie planted on an attacker-controlled ``*-salesforce.com`` host
    would be classified as Salesforce and could bind the connector to it.
    """
    h = host.lstrip(".").lower()
    return (
        h == "salesforce.com"
        or h.endswith(".salesforce.com")
        or h == "force.com"
        or h.endswith(".force.com")
    )
