# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Parse Safari's ``Cookies.binarycookies`` file on macOS.

Format (big-endian header, little-endian page/cookie fields):
  - magic ``cook``
  - int32 BE page count, then page count × int32 BE page sizes
  - each page: int32 ``0x00000100``, int32 LE cookie count, cookie-count ×
    int32 LE cookie offsets (relative to page start), int32 footer, cookies
  - each cookie: int32 LE record size, ... int32 LE offsets to url/name/path/
    value (relative to record start), null-terminated strings at those offsets

Reading the file requires Full Disk Access for the host process.
"""

from __future__ import annotations

import logging
import struct

from .browsers import CookieSource
from .instance import is_salesforce_host
from .utils import best_host_match

log = logging.getLogger(__name__)

__all__ = ["list_salesforce_sids", "read_safari_cookie", "parse_binarycookies"]


def list_salesforce_sids(source: CookieSource) -> list[tuple[str, str]]:
    """Return all ``(host, sid)`` Salesforce session cookies in this store."""
    try:
        data = source.path.read_bytes()
    except (FileNotFoundError, PermissionError):
        return []
    try:
        cookies = parse_binarycookies(data)
    except (ValueError, struct.error, IndexError):
        return []
    return [
        (host, value)
        for (host, name, value) in cookies
        if name == "sid" and value and is_salesforce_host(host)
    ]


def read_safari_cookie(source: CookieSource, host: str, name: str) -> str | None:
    """Return cookie `name` for `host` from Safari's cookie store, or None."""
    try:
        data = source.path.read_bytes()
    except (FileNotFoundError, PermissionError) as e:
        log.warning("Safari cookie file unreadable (%s): %s", type(e).__name__, e)
        return None
    try:
        cookies = parse_binarycookies(data)
    except (ValueError, struct.error, IndexError) as e:
        log.warning("Safari cookie parse failed: %s: %s", type(e).__name__, e)
        return None

    # Require a non-empty value; binarycookies stores values in plaintext.
    candidates = [(h, v) for (h, n, v) in cookies if n == name]
    match = best_host_match(
        candidates, host, host_of=lambda r: r[0], eligible=lambda r: bool(r[1])
    )
    return match[1] if match else None


def parse_binarycookies(data: bytes) -> list[tuple[str, str, str]]:
    """Parse a binarycookies blob into a list of ``(host, name, value)``."""
    if data[:4] != b"cook":
        raise ValueError("not a binarycookies file (bad magic)")
    num_pages = struct.unpack(">i", data[4:8])[0]
    page_sizes = [
        struct.unpack(">i", data[8 + 4 * i : 12 + 4 * i])[0] for i in range(num_pages)
    ]
    offset = 8 + 4 * num_pages
    out: list[tuple[str, str, str]] = []
    for size in page_sizes:
        out.extend(_parse_page(data[offset : offset + size]))
        offset += size
    return out


def _parse_page(page: bytes) -> list[tuple[str, str, str]]:
    num_cookies = struct.unpack("<i", page[4:8])[0]
    offsets = [
        struct.unpack("<i", page[8 + 4 * i : 12 + 4 * i])[0] for i in range(num_cookies)
    ]
    out: list[tuple[str, str, str]] = []
    for off in offsets:
        record = page[off:]
        url_off = struct.unpack("<i", record[16:20])[0]
        name_off = struct.unpack("<i", record[20:24])[0]
        value_off = struct.unpack("<i", record[28:32])[0]
        host = _read_cstr(record, url_off)
        name = _read_cstr(record, name_off)
        value = _read_cstr(record, value_off)
        out.append((host, name, value))
    return out


def _read_cstr(buf: bytes, offset: int) -> str:
    end = buf.index(b"\x00", offset)
    return buf[offset:end].decode("utf-8", errors="replace")
