# Generated by OrchestKit Claude Plugin
# Created: 2026-06-29

"""Resolve a browser-matching User-Agent for outgoing Salesforce API calls.

`simple_salesforce` / `requests` default to a `python-requests/x.y` User-Agent.
Against an org we authenticate to by lifting the browser's live `sid` cookie,
that bot UA is an obvious mismatch from the Chrome UA the same session uses
interactively — easy for Salesforce to fingerprint as non-browser traffic. We
send a real browser UA instead so the MCP requests look like the browser they
piggyback on.

Resolution order (first hit wins):
  1. ``SALESFORCE_USER_AGENT`` env — explicit override.
  2. Live UA from a running browser's DevTools endpoint. Chromium browsers
     expose ``/json/version`` on their remote-debugging port; Comet launches on
     9222, so it matches the actual browser and tracks version bumps for free.
  3. A pinned current-Chrome fallback string (only the major needs occasional
     bumping — browsers freeze the rest at ``.0.0.0``).
"""

from __future__ import annotations

import json
import logging
import os
from collections.abc import Iterable, Mapping
from urllib.error import URLError
from urllib.request import urlopen

log = logging.getLogger(__name__)

ENV_VAR = "SALESFORCE_USER_AGENT"

# Pinned fallback: a current desktop-Chrome UA. Browsers report the reduced
# `Chrome/<major>.0.0.0` form, so only the major needs the occasional bump.
# Matches what Comet (Chromium-based) advertises.
FALLBACK_UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36"
)

# DevTools remote-debugging ports to probe, in order. Comet launches on 9222.
_DEFAULT_CDP_PORTS: tuple[int, ...] = (9222,)


def _ua_from_cdp(port: int, timeout: float = 1.0) -> str | None:
    """Return the live browser User-Agent from a DevTools endpoint, or None.

    Hits ``http://127.0.0.1:<port>/json/version`` (the unauthenticated CDP
    metadata endpoint). Any failure — port closed, non-JSON, missing field —
    yields None so the caller falls through to the next source.
    """
    url = f"http://127.0.0.1:{port}/json/version"
    try:
        with urlopen(url, timeout=timeout) as resp:  # noqa: S310 — fixed localhost URL
            data = json.loads(resp.read().decode("utf-8"))
    except (URLError, OSError, ValueError):
        return None
    ua = data.get("User-Agent") if isinstance(data, dict) else None
    if not isinstance(ua, str) or "Mozilla" not in ua:
        return None
    # A browser launched headless reports "HeadlessChrome"/"Headless"; strip it
    # so we never advertise automation in the UA we forward to Salesforce.
    return ua.replace("HeadlessChrome", "Chrome").replace("Headless", "").strip()


def resolve_user_agent(
    env: Mapping[str, str] | None = None,
    cdp_ports: Iterable[int] = _DEFAULT_CDP_PORTS,
) -> str:
    """Resolve the browser-matching UA: env override → live CDP → pinned fallback.

    Resolved once at patch-install time and reused for every call, so the live
    CDP probe costs at most one short localhost request at startup.
    """
    env = os.environ if env is None else env
    override = (env.get(ENV_VAR) or "").strip()
    if override:
        log.info("User-Agent: using %s override", ENV_VAR)
        return override
    for port in cdp_ports:
        ua = _ua_from_cdp(port)
        if ua:
            log.info("User-Agent: matched live browser via DevTools port %d", port)
            return ua
    log.info("User-Agent: no live browser found; using pinned Chrome fallback")
    return FALLBACK_UA
