# Generated by OrchestKit Claude Plugin
# Created: 2026-06-22

"""Shared helpers for the per-browser cookie readers.

Both the host-suffix matcher and the SQLite cookie query were copy-pasted across
``chromium.py``, ``firefox.py``, and ``safari.py`` and had begun to diverge.
Centralizing them here keeps the matching/query semantics identical across
browsers (the value-eligibility difference is now an explicit parameter rather
than an accidental per-file variation).

This module imports only the standard library, so the readers can depend on it
without creating an import cycle with ``cookies.py``.
"""

from __future__ import annotations

import logging
import shutil
import sqlite3
import tempfile
from collections.abc import Callable, Iterable, Sequence
from pathlib import Path
from typing import TypeVar

log = logging.getLogger(__name__)

__all__ = ["best_host_match", "query_sqlite_cookies"]

_Row = TypeVar("_Row")


def best_host_match(
    rows: Iterable[_Row],
    host: str,
    *,
    host_of: Callable[[_Row], str],
    eligible: Callable[[_Row], bool] = lambda _row: True,
) -> _Row | None:
    """Return the row whose host is the longest suffix-match of ``host``.

    A row matches when ``host`` equals the row's bare host (leading dots stripped,
    lowercased) or ends with ``.<bare host>``. Among matches, the one with the
    longest bare host wins (the most specific domain). Rows for which ``eligible``
    returns False are skipped entirely — so a shorter eligible row beats a longer
    ineligible one.

    Args:
        rows: Candidate rows in any shape.
        host: The target host to match against (e.g. ``acme.my.salesforce.com``).
        host_of: Extracts the host string from a row.
        eligible: Optional filter; default accepts every row. Chromium accepts
            all matches (its value may live in an encrypted column), while the
            plaintext readers require a non-empty value.
    """
    target = host.lower()
    best: _Row | None = None
    best_len = -1
    for row in rows:
        bare = host_of(row).lstrip(".").lower()
        if (target == bare or target.endswith("." + bare)) and eligible(row):
            if len(bare) > best_len:
                best = row
                best_len = len(bare)
    return best


def query_sqlite_cookies(
    db_path: Path, sql: str, params: Sequence[object] = ()
) -> list[tuple] | None:
    """Copy a (possibly locked) cookie DB to a temp file and run a read-only query.

    Browsers hold their cookie SQLite DB open with a write lock, so we copy it to
    a temp directory first and open the copy read-only. Returns the raw rows, or
    ``None`` if the DB can't be copied or read (callers defer auth errors to
    tool-call time rather than raising at startup).
    """
    try:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_db = Path(tmp) / db_path.name
            shutil.copy2(db_path, tmp_db)
            con = sqlite3.connect(f"file:{tmp_db}?mode=ro", uri=True)
            try:
                return list(con.execute(sql, params).fetchall())
            finally:
                con.close()
    except (OSError, sqlite3.Error) as e:
        log.warning(
            "cookie DB read failed for %s: %s: %s", db_path, type(e).__name__, e
        )
        return None
