# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

"""Validate a Salesforce ``sid`` against the REST API.

Used during auto-discovery to pick, among several candidate sessions found in
the browser cookie stores, one that is actually live. A single authenticated
GET to ``/services/data/vNN/limits`` returns 200 for a valid session and 401
for an expired/wrong one (e.g. a Lightning sid used against the My Domain host).
"""

from __future__ import annotations

import logging
from urllib.request import Request, urlopen

log = logging.getLogger(__name__)

_API_VERSION = "62.0"


def session_is_valid(instance_url: str, sid: str, timeout: float = 8.0) -> bool:
    """Return True if `sid` authorizes REST calls against `instance_url`.

    Any non-200 response, HTTP error, or network failure yields ``False`` —
    a session we cannot positively confirm is treated as unusable.
    """
    url = f"{instance_url}/services/data/v{_API_VERSION}/limits"
    req = Request(url, headers={"Authorization": f"Bearer {sid}"})
    try:
        with urlopen(req, timeout=timeout) as resp:
            return getattr(resp, "status", None) == 200
    except Exception as e:  # noqa: BLE001 — any failure means "not usable"
        log.info(
            "session validation failed for %s: %s: %s",
            instance_url,
            type(e).__name__,
            e,
        )
        return False
