# Generated by OrchestKit Claude Plugin
# Created: 2026-06-19

#!/usr/bin/env -S uv run python
"""End-to-end smoke test for the auto-auth path.

Resolves a session exactly like `__main__` does (auto-discovery or a configured
URL), installs the per-call refresh patch, then runs a REAL authenticated SOQL
query through `simple_salesforce` — with a deliberately wrong construction-time
token, to prove the patch injects the correct one per call.

Run before publishing:

    uv run scripts/smoke.py                              # auto-discover an org
    uv run scripts/smoke.py https://acme.lightning.force.com   # pin one

Exits 0 on a successful query, 1 otherwise. Requires being logged into a
Salesforce org in a supported browser (first run may prompt a one-time Keychain
"Always Allow").
"""

from __future__ import annotations

import logging
import sys

from salesforce_mcp_auto_auth_chrome.orgs import resolve_session
from salesforce_mcp_auto_auth_chrome.patch import install


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    configured = sys.argv[1] if len(sys.argv) > 1 else None

    resolved = resolve_session(configured)
    if not resolved.instance_url:
        print("SMOKE FAIL: no org configured and none auto-detected.", file=sys.stderr)
        return 1
    pin = f"{resolved.browser}/{resolved.profile}" if resolved.browser else "any"
    print(f"resolved {resolved.instance_url} (pinned to {pin})", file=sys.stderr)
    if not resolved.sid:
        print("SMOKE FAIL: no sid for the resolved org.", file=sys.stderr)
        return 1

    install(
        resolved.instance_url,
        pin_browser=resolved.browser,
        pin_profile=resolved.profile,
    )

    from simple_salesforce import Salesforce

    # Construct with a wrong token on purpose; the patch must override it.
    sf = Salesforce(
        instance_url=resolved.instance_url,
        session_id="WRONG_STALE_TOKEN",
        version="62.0",
    )
    records = sf.query("SELECT Id, Name FROM Account LIMIT 1")["records"]
    if not records:
        print("SMOKE WARN: query returned no Accounts (auth OK, org empty).")
        return 0
    print(f"SMOKE OK: authenticated query returned Account {records[0]['Name']!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
